name: Run headless unit tests with pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # Install dependencies for running tests without a display (Xvfb and pytest-xvfb plugin)
    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install -y \
          xvfb \
          libxkbcommon-x11-0 \
          pyqt5-dev-tools

        python -m pip install --upgrade pip
        pip install pytest-xvfb
        pip install -r requirements.txt
    
    - name: Run tests
      # Create a dummy config.toml to be loaded on startup
      run: |
        cp config.tmpl.toml config.toml
        pytest